# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: @/plugins/whsol/reservation/models/month/columns.yaml

# Model Class name
modelClass: WhSol\Reservation\Models\Month

# List Title
title: whsol.reservation::lang.month.title

# Link URL for each record
recordUrl: whsol/reservation/month/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 12

defaultSort:
  column: month_name
  direction: asc

# Display checkboxes next to each record
# showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt



